### PR TITLE
Add support for four positions

### PR DESCRIPTION
**Pull request by bag-man**
Sorry to make it on Github not Gitlab, but hopefully you can merge it still. 

This allows you to have the terminal in the top or left of your window, just by extending the number of positions to four. 

Hope you like! @Lenovsky

### CODE REVIEW

**Comment by lenowski** [comment]
Thanks for your work, before I can merge it we need to make some small changes:

1.  Because we are adding more positions, I think it would be more intuitive to rely on self-explanatory strings instead of numbers. It may look like this:
```
let g:nuake_position = {position} (default 'bottom')
    Set the Nuake position to 'bottom',  'right',  'top' or 'left'.
```
2. Commit 34831a2 contains helptags (`doc/tag`), which shouldn't be present. 
3. Commit 5443fad is unrelated. Also, I'm not sure if we should mess with global options - this may be annoying for people who like `syntax off` feeling. Please exclude this for now.

After all this, we will be ready to go ;)

**Comment by bag-man** [comment]
Sorted!

**Comment by bag-man** [comment]
I have added syntax as an option, and fixed a bug where the terminal was killed. 

For clarity on the syntax thing, by default when you exit terminal mode and enter normal mode, I loose colours (syntax highlighting), which looks really ugly. This option allows you to keep colours in normal mode.

**Comment by lenowski** [comment]
Thanks for the clarification. To be honest, I can’t reproduce colour loss, please post an [issue](https://gitlab.com/Lenovsky/nuake/issues) with related config and steps to reproduce. If we fail to fix it without any special configuration, I’ll apply the proposed solution.

The rest looks good I’ll merge as soon as you exclude the colour loss stuff.

**Comment by bag-man** [comment]
Removed it, I tracked it down to an issue with another plugin! So glad I fixed the state loss bug, that was driving me up the wall!

**Comment by bag-man** [comment]
I fixed a regression, so double check it's okay. The regression was if you opened Nuake, then opened a new tab, then closed that new tab, an error would occur.

**Pull request merged**
